create database student;
use student;
create table if not exists student_uet(id int primary key not null auto_increment, studentID varchar(10), student_name varchar(30), university varchar(20), mark float);
create table if not exists student_ulis(id int primary key not null auto_increment, studentID varchar(10), student_name varchar(30), university varchar(20), mark float);
create table if not exists student_hus(id int primary key not null auto_increment, studentID varchar(10), student_name varchar(30), university varchar(20), mark float);
create table if not exists student_ueb(id int primary key not null auto_increment, studentID varchar(10), student_name varchar(30), university varchar(20), mark float);

insert into student_uet(studentID, student_name, university, mark) values ("09020232", "Le Van Hung", "UET", 8.9);
insert into student_uet(studentID, student_name, university, mark) values ("09020210", "Nguyen Van A", "UET", 8.1);
insert into student_uet(studentID, student_name, university, mark) values ("09020211", "Tran Thi B", "UET", 7.5);
insert into student_uet(studentID, student_name, university, mark) values ("09020212", "Nguyen Van C", "UET", 6.2);
insert into student_uet(studentID, student_name, university, mark) values ("09020213", "Le Van Tam", "UET", 6.7);
insert into student_uet(studentID, student_name, university, mark) values ("09020214", "Tran Thi Tam", "UET", 4.1);
insert into student_uet(studentID, student_name, university, mark) values ("09020215", "Do Manh Hung", "UET", 5.2);
insert into student_uet(studentID, student_name, university, mark) values ("09020216", "Hoang Van Nam", "UET", 9.2);
insert into student_uet(studentID, student_name, university, mark) values ("09020217", "Do Van Tung", "UET", 7.6);
insert into student_uet(studentID, student_name, university, mark) values ("09020218", "Ngo Ngoc Nam", "UET", 7.2);
insert into student_uet(studentID, student_name, university, mark) values ("09020233", "Cao Thi Lan", "UET", 5.8);
insert into student_ulis(studentID, student_name, university, mark) values ("09010232", "Le Van Hung1", "ULIS", 6.5);
insert into student_ulis(studentID, student_name, university, mark) values ("09010210", "Nguyen Van A1", "ULIS", 6.4);
insert into student_ulis(studentID, student_name, university, mark) values ("09010211", "Tran Thi B1", "ULIS", 9.2);
insert into student_ulis(studentID, student_name, university, mark) values ("09010212", "Nguyen Van C1", "ULIS", 8.9);
insert into student_ulis(studentID, student_name, university, mark) values ("09010213", "Le Van Tam1", "ULIS", 9.1);
insert into student_ulis(studentID, student_name, university, mark) values ("09010214", "Tran Thi Tam1", "ULIS", 9.6);
insert into student_ulis(studentID, student_name, university, mark) values ("09020215", "Do Manh Hung1", "ULIS", 8.4);
insert into student_ulis(studentID, student_name, university, mark) values ("09010216", "Hoang Van Nam1", "ULIS", 7.5);
insert into student_ulis(studentID, student_name, university, mark) values ("09010217", "Do Van Tung1", "ULIS", 7.2);
insert into student_ulis(studentID, student_name, university, mark) values ("09010218", "Ngo Ngoc Nam1", "ULIS", 6.7);
insert into student_ulis(studentID, student_name, university, mark) values ("09010233", "Cao Thi Lan1", "ULIS", 8.4);
insert into student_hus(studentID, student_name, university, mark) values ("09030232", "Le Van Hung", "HUS", 6.5);
insert into student_hus(studentID, student_name, university, mark) values ("09030210", "Nguyen Van A2", "HUS", 6.7);
insert into student_hus(studentID, student_name, university, mark) values ("09030211", "Tran Thi B2", "HUS", 9.4);
insert into student_hus(studentID, student_name, university, mark) values ("09030212", "Nguyen Van C2", "HUS", 9.2);
insert into student_hus(studentID, student_name, university, mark) values ("09030213", "Le Van Tam", "HUS", 7.6);
insert into student_hus(studentID, student_name, university, mark) values ("09030214", "Tran Thi Tam2", "HUS", 8.1);
insert into student_hus(studentID, student_name, university, mark) values ("09030215", "Do Manh Hung2", "HUS", 8.3);
insert into student_hus(studentID, student_name, university, mark) values ("09030216", "Hoang Van Nam2", "HUS", 7.8);
insert into student_hus(studentID, student_name, university, mark) values ("09030217", "Do Van Tung2", "HUS", 8.9);
insert into student_hus(studentID, student_name, university, mark) values ("09030218", "Ngo Ngoc Nam2", "HUS", 8.4);
insert into student_ueb(studentID, student_name, university, mark) values ("09040232", "Le Van Hung3", "UEB", 6.6);
insert into student_ueb(studentID, student_name, university, mark) values ("09040210", "Nguyen Van A3", "UEB", 7.5);
insert into student_ueb(studentID, student_name, university, mark) values ("09040211", "Tran Thi B3", "UEB", 7.9);
insert into student_ueb(studentID, student_name, university, mark) values ("09040212", "Nguyen Van C3", "UEB", 6.4);
insert into student_ueb(studentID, student_name, university, mark) values ("09040213", "Le Van Tam3", "UEB", 9.2);
insert into student_ueb(studentID, student_name, university, mark) values ("09040214", "Tran Thi Tam3", "UEB", 7.1);
insert into student_ueb(studentID, student_name, university, mark) values ("09040215", "Do Manh Hung3", "UEB", 8.7);
insert into student_ueb(studentID, student_name, university, mark) values ("09040216", "Hoang Van Nam3", "UEB", 8.3);
insert into student_ueb(studentID, student_name, university, mark) values ("09040217", "Do Van Tung3", "UEB", 7.8);
insert into student_ueb(studentID, student_name, university, mark) values ("09040218", "Ngo Ngoc Nam3", "UEB", 9.6);
insert into student_uet(studentID, student_name, university, mark) values ("09010233", "Cao Thi Lan1", "ULIS", 8.4);